### ISSUE TITLE
range parser should ignore incorrect range headers

### ISSUE THREAD

**Issue by bdkock-geosolutions** [OnroerendErfgoed/oe_utils#13]
If my interpretation of RFC 2616 is correct then incorrect range headers should be ignored. Specifically, if the end of the range precedes the start then the range header should be ignored.

The parser of range headers though doesn't seem to comply to this. (see `range_parser.py`) Instead it 'fixes' the value of such a range header by doing the following:

```
                if end < start:
                    end = start
```

In my opinion this is unnecessary. Incorrect range headers shouldn't be created in the first place. And I certainly don't like extra logic only for the sake of hiding errors. Or is there something else that I need to consider, but am not aware of yet?

**Comment by koenedaele** [comment]
We actually DO ignore the range header. We just decide ourselves what range to send back. Specifically because I do not want to fall back on sending back everything. We could fall back on the default range (ie. 0-11), but in this case we're falling back on start-start. In the end, neither falling back on the default or on start-start is very useful to the client. But, the client should never assume that the ranges it requested is the range it will receive. It's a suggestion to the server and the server is free to ignore it and decide on something else (eg. when the client does not specify a range we return 0-11). So, the server gets to decide how much of the collection it sends back and it's up to the client to deal with this.

Only other possibility I see here is returning a 400 Bad Request. Possibly by turning this into a RangeParseException and having that be a subclass of HTTP 400 Bad Request.

**Comment by bdkock-geosolutions** [comment]
Hmm, I see your point. After some pondering it turns out I can't decide which solution is better. In that case by principle my opinion has become to leave things as they are currently.

**Comment by koenedaele** [comment]
@BartSaelen Feel free to come back to this after april fools to decide if we want to change anything.
