### ISSUE TITLE
Revert Wijzigingshistoriek commits

### ISSUE THREAD

**Issue by cahytinne** [OnroerendErfgoed/oe_utils#83]
The commits involving the history logging are not backwards compatible. It will result in too much conflicts when upgrading oe_utils module in other libraries. It needs to be reverted.

**Comment by goessebr** [comment]
Correct. @Mattivm reported this and made an issue to fix the backward compatibility: https://github.com/OnroerendErfgoed/oe_utils/issues/79.

Since the handling of multiple resources will be handled on a different matter, the previous changes are no longer needed and a reversion is preferred.

A change of the field resource_id to resource_uri in the table would be a nice refactoring to handle multiple resources more cleanly but can be fixed in the future.
A possibility with a smaller impact is to make the Wijziging table and decorator deprecated and make new functionalities that will use a URI as resource identifier.
